apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "database.fullname" . }}-backups
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.backup.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.backup.storage.size }}
