{{- if not .Values.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-secret
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.auth.password | quote }}
  POSTGRES_USER: {{ .Values.auth.username | quote }}
  POSTGRES_DB: {{ .Values.auth.database | quote }}
{{- end }}
