frontend:
  replicaCount: 2

  image:
    repository: task-management-frontend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8080

  ingress:
    enabled: true
    host: task-management.local

  backendServiceUrl: "http://release-name-backend:3000"

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

  pdb:
    minAvailable: 1
